In [ ]:
import numpy as np

#Neuronal Networks (Welch Lab)

##Part 1: Data and Architecture

We can predict some output $Y$ from a collection of data $X$ in matrix structure. For the example: $X$ is the matrix of hours sleeping and hours studying where $V_n$ is the colunm vector of inputs vars to the model.

$$X=M\{V_1,V_2,...,V_n\}$$

Another form to represent it: if $n$ is the number of samples to make the regression and $m$ is the amount of input variables (hours sleeping, hours studying).

$$X=M_{n\times m}$$

The $Y$ is a colunm matrix which map every entry of X (row) and its the output for the respective input.

$$Y=M_{n\times 1}$$

Some personal notation a will use to represent the transformation as a function where $f$ is the real system:

$$f(X)\rightarrow Y$$

The regression case will represented as:

$$NN(X) → \hat{Y}$$

In [ ]:
X = np.array(([3,5], [5,1], [10,2]), dtype=float)
Y = np.array(([75], [82], [93]), dtype=float)

In [ ]:
X

array([[ 3.,  5.],
       [ 5.,  1.],
       [10.,  2.]])

In [ ]:
Y

array([[75.],
       [82.],
       [93.]])

The first need is take data and normalized it to [0,1] range, minimal values will perform operations.

In [ ]:
X = np.divide(X, np.amax(X, axis=0))
Y = np.divide(Y, 100)

In [ ]:
X

array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [ ]:
Y

array([[0.75],
       [0.82],
       [0.93]])